# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import nltk

import nltk

nltk.download('all')

from nltk.book import *

from nltk.corpus import brown

brown.words(categories='adventure')[:50]

from nltk.corpus import inaugural

inaugural.fileids()

inaugural.words(fileids='1861-Lincoln.txt')[:20]

inaugural.words(fileids='2017-Trump.txt')[:20]

text1='The basis for the work is melvilles 1841'

fd=nltk.FreqDist(text1.split())

fd

